### ISSUE TITLE
请教一个关于运行效率的问题。

### ISSUE THREAD

**Issue by xhxt2008** [12wang3/rrl#10]
请教一下，我用您的测试数据可以跑得起来，但是执行效率看起来有点低，您是否知道可能是什么问题，如何排查。

- 998条数据的tic-tac-toe数据集，一个epoch看起来需要5min

![image](https://github.com/12wang3/rrl/assets/11420723/1cb0784e-5c2c-4bda-baf5-7470381e4f3b)

- GPU看起来完全没有用起来，使用率一直是0，但是显存被使用了

![image](https://github.com/12wang3/rrl/assets/11420723/84e659c2-47be-4da3-b42c-52b4115670d3)

- Loss看起来也正常在下降，但是效率看起来太低了。
![image](https://github.com/12wang3/rrl/assets/11420723/4d949d98-64e8-4e71-a110-cf78b563219d)

想请教一下您，这样的执行效率是否正常，是否是可能因为环境问题或者配置错误导致的效率低下呢。

**Comment by 12wang3** [comment]
看描述比较奇怪，tic-tac-toe数据集的话，正常来说400个epoch可能也用不了5min。猜测是torch或者CUDA的版本问题，可以尝试换一个版本。

**Comment by xhxt2008** [comment]
研究了一下，这个问题应该是我这边环境的问题，不是代码本身的问题。
