### ISSUE TITLE
您好，我有一个初级的问题想要请教一些您，希望可以得到回复

### ISSUE THREAD

**Issue by nannan789** [12wang3/rrl#11]
在对连续数据进行运行代码的时候，会出现维度不匹配的问题，但是我实在是没看懂t()是什么函数，是什么意思，希望这里的问题可以被解答。
![1](https://github.com/12wang3/rrl/assets/80943216/50e7b9df-b8ea-449a-acc1-5614330d8662)

**Comment by 12wang3** [comment]
t()是转置操作。不过看你这个报错应该是BinarizeLayer的配置设置错了或者输入有问题。你可以在binarize_res = Binarize.apply(x - self.cl.t()).view(x.shape[0], -1)这一句的上面输出一下x.shape和self.cl.t().shape看看就知道是哪个错了。

**Comment by nannan789** [comment]
感谢回复，目前问题我已解决，再次感谢。
