### ISSUE TITLE
您好，想咨询您关于更新版本的一个问题，希望得到回复

### ISSUE THREAD

**Issue by tua123** [12wang3/rrl#12]
看到您的Readme，您有说要将更新的内容交给TPAMI审查，我想请问您有没有发布对应的arxiv？

**Comment by 12wang3** [comment]
目前还没传，我整理一下这周末传到arxiv上

**Comment by 12wang3** [comment]
论文昨天被TPAMI接收了，预印本见https://arxiv.org/abs/2310.14336

**Comment by tua123** [comment]
> 论文昨天被TPAMI接收了，预印本见https://arxiv.org/abs/2310.14336

恭喜恭喜

**Comment by 12wang3** [comment]
> > 论文昨天被TPAMI接收了，预印本见https://arxiv.org/abs/2310.14336
> 
> 恭喜恭喜

谢谢！
