### ISSUE TITLE
Rules generated for each dataset

### ISSUE THREAD

**Issue by frankl1** [12wang3/rrl#18]
Hi,
I am trying to have a look to the rules generated for each dataset in the paper but could do not find them. Do you think you can make these rules public? 
Regards

**Comment by 12wang3** [comment]
For different datasets, different parameters correspond to different rules. You can try to run the code yourself to generate rules.

**Comment by frankl1** [comment]
Thanks for replying back. I understand, I was hopping that you could share the rules you obtained during your experiment with your set of hyperparameters. This way I can try to reproduce the same set of rules on my side. Feel free to close this issue if you don't have the rules stored somewhere already.
Thanks
