### ISSUE TITLE
Running the demo on the Windows11

### ISSUE THREAD

**Issue by AwaisKhan5647** [12wang3/rrl#19]
By fixing all the linux and distributed GPU issues I am stuck on the following error:
 
 No such file or directory: b'log_folder\\tic-tac-toe\\tic-tac-toe_e401_bs32_lr0.002_lrdr0.75_lrde200_wd0.0001_ki0_rc0_useNOTFalse_saveBestFalse_useNLAFFalse_estimatedGradFalse_useSkipFalse_alpha0.999_beta8_gamma1_temp1.0_L1@16\\events.out.tfevents.1729130715.525-3660-06.11504.0'

Although the rrl directory have the following files but one is missing:

'log_folder\\tic-tac-toe\\tic-tac-toe_e401_bs32_lr0.002_lrdr0.75_lrde200_wd0.0001_ki0_rc0_useNOTFalse_saveBestFalse_useNLAFFalse_estimatedGradFalse_useSkipFalse_alpha0.999_beta8_gamma1_temp1.0_L1@16\\"

The folder is empty and the required file is missing.

**Comment by 12wang3** [comment]
Windows has a limit on the length of the file path, so the file cannot be found. Linux does not have this problem. If running on Windows, you can try to modify the code to shorten the file path (i.e., shorten 'rrl_args.folder_name' in 'args.py').

**Comment by AwaisKhan5647** [comment]
yes, that was the issue I just switched to Linux and now its working.
