### ISSUE TITLE
参数问题

### ISSUE THREAD

**Issue by 1137292294** [12wang3/rrl#7]
您好，我是一名计算机专业大四学生，正在复现这个实验，其他的数据集没有跑出预期的效果，请问可以麻烦您提供下其他数据集的参数配置吗，麻烦了，谢谢您！

**Comment by 12wang3** [comment]
感谢对我们工作的关注！以下命令可供参考：
python3 experiment.py -d adult -bs 32 -s 10@512 -e401 -lrde 200 -lr 0.0001 -ki 0 -mp 12450 -i 0 -wd 1e-7 --save_best &
python3 experiment.py -d bank-marketing -bs 32 -s 10@256 -e401 -lrde 200 -lr 0.0002 -ki 0 -mp 12480 -i 0 -wd 1e-7 --save_best &
其他数据集命令类似，但特征数较多的数据集请加上--estimated_grad。将-ki的值从0设置到4，即可进行5折交叉验证。另外请按照README中“DataSetDesc”里的要求下载和设置.data以及.info文件。

**Comment by qizhou000** [comment]
你好！请问-e401是什么参数？

**Comment by 12wang3** [comment]
> 你好！请问-e401是什么参数？

-e用于设置epoch，您可以使用python3 experiment.py --help来查看各个参数的含义。

**Comment by qizhou000** [comment]
> > 你好！请问-e401是什么参数？
> 
> -e用于设置epoch，您可以使用python3 experiment.py --help来查看各个参数的含义。

谢谢

**Comment by qizhou000** [comment]
请问论文中训练每个数据集的超参数能都提供一下吗？表1的

**Comment by bakachan19** [comment]
Hi. I am also interested in the hyperparameters for training each data set in the paper.
Thanks.
